package visuadura;

import ligadura.Conequisaum;
import javax.swing.JOptionPane;

public class update_pt2 extends javax.swing.JFrame {

    /**
     * Creates new form cradastu
     */
    public update_pt2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        número_lbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        número_txt = new javax.swing.JTextPane();
        nome_lbl = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        nome_txt = new javax.swing.JTextPane();
        tipo_lbl = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tipo_txt = new javax.swing.JTextPane();
        evolução_lbl = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        evolução_txt = new javax.swing.JTextPane();
        região_lbl = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        região_txt = new javax.swing.JTextPane();
        Sair = new javax.swing.JButton();
        Limpar = new javax.swing.JButton();
        Enviar = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        P_evolução_txt = new javax.swing.JTextPane();
        P_evolução_lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        painel.setBackground(new java.awt.Color(0, 0, 204));

        titulo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 0, 51));
        titulo.setText("Update");

        número_lbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        número_lbl.setForeground(new java.awt.Color(255, 255, 255));
        número_lbl.setText("Número");

        número_txt.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        jScrollPane1.setViewportView(número_txt);

        nome_lbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nome_lbl.setForeground(new java.awt.Color(255, 255, 255));
        nome_lbl.setText("Nome");

        nome_txt.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        jScrollPane2.setViewportView(nome_txt);

        tipo_lbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tipo_lbl.setForeground(new java.awt.Color(255, 255, 255));
        tipo_lbl.setText("Tipo(s)");

        tipo_txt.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        jScrollPane3.setViewportView(tipo_txt);

        evolução_lbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        evolução_lbl.setForeground(new java.awt.Color(255, 255, 255));
        evolução_lbl.setText("Evolução");

        evolução_txt.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        jScrollPane4.setViewportView(evolução_txt);

        região_lbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        região_lbl.setForeground(new java.awt.Color(255, 255, 255));
        região_lbl.setText("Região originária");

        região_txt.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        jScrollPane5.setViewportView(região_txt);

        Sair.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Sair.setText("Sair");
        Sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SairMouseClicked(evt);
            }
        });

        Limpar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Limpar.setText("Limpar");
        Limpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LimparMouseClicked(evt);
            }
        });

        Enviar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Enviar.setText("Enviar");
        Enviar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EnviarMouseClicked(evt);
            }
        });

        P_evolução_txt.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        jScrollPane6.setViewportView(P_evolução_txt);

        P_evolução_lbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        P_evolução_lbl.setForeground(new java.awt.Color(255, 255, 255));
        P_evolução_lbl.setText("Pré evolução");

        javax.swing.GroupLayout painelLayout = new javax.swing.GroupLayout(painel);
        painel.setLayout(painelLayout);
        painelLayout.setHorizontalGroup(
            painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelLayout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelLayout.createSequentialGroup()
                            .addComponent(região_lbl)
                            .addGap(18, 18, 18)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelLayout.createSequentialGroup()
                            .addComponent(evolução_lbl)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(painelLayout.createSequentialGroup()
                        .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(número_lbl)
                            .addComponent(nome_lbl)
                            .addComponent(tipo_lbl))
                        .addGap(87, 87, 87)
                        .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(painelLayout.createSequentialGroup()
                        .addComponent(P_evolução_lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42))
            .addGroup(painelLayout.createSequentialGroup()
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(Limpar)
                        .addGap(18, 18, 18)
                        .addComponent(Enviar)
                        .addGap(18, 18, 18)
                        .addComponent(Sair))
                    .addGroup(painelLayout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(titulo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelLayout.setVerticalGroup(
            painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(titulo)
                .addGap(31, 31, 31)
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(número_lbl)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nome_lbl)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipo_lbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P_evolução_lbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(evolução_lbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(região_lbl)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sair)
                    .addComponent(Limpar)
                    .addComponent(Enviar))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SairMouseClicked
        System.exit(0);
    }//GEN-LAST:event_SairMouseClicked

    private void LimparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LimparMouseClicked
        nome_txt.setText("");
        número_txt.setText("");
        tipo_txt.setText("");
        evolução_txt.setText("");
        região_txt.setText("");
    }//GEN-LAST:event_LimparMouseClicked

    private void EnviarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EnviarMouseClicked
        try{
            String numero = número_txt.getText();
            Integer número = Integer.parseInt(numero);
            String nome = nome_txt.getText();
            String tipo = tipo_txt.getText();
            String evolução = evolução_txt.getText();
            String pré_evolução = P_evolução_txt.getText();
            String região = região_txt.getText();

            Conequisaum envio = new Conequisaum();
            
            
            if(número == null){
                JOptionPane.showMessageDialog(this, "Garanta de preencher todos os espaços necessários para o cadastro!");
            }else{
                envio.atualizar(número,nome, tipo, evolução,pré_evolução, região);
                JOptionPane.showMessageDialog(this, "Dado atualizado com sucesso!");
                envio.fechar();
            }
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Número Inválido! Tente Novamente");
        }
    }//GEN-LAST:event_EnviarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(update_pt2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(update_pt2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(update_pt2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(update_pt2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new update_pt2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Enviar;
    private javax.swing.JButton Limpar;
    private javax.swing.JLabel P_evolução_lbl;
    private javax.swing.JTextPane P_evolução_txt;
    private javax.swing.JButton Sair;
    private javax.swing.JLabel evolução_lbl;
    private javax.swing.JTextPane evolução_txt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel nome_lbl;
    private javax.swing.JTextPane nome_txt;
    private javax.swing.JLabel número_lbl;
    private javax.swing.JTextPane número_txt;
    private javax.swing.JPanel painel;
    private javax.swing.JLabel região_lbl;
    private javax.swing.JTextPane região_txt;
    private javax.swing.JLabel tipo_lbl;
    private javax.swing.JTextPane tipo_txt;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
